language: minimal
sudo: required
services:
  - docker
before_install:
  - docker pull debian:buster-slim
  - docker run --name build --rm --detach --interactive --mount type=bind,src=`pwd`,dst=/build debian:buster-slim /bin/sh
  - docker ps -a
  - docker exec -u root build apt-get -q -y update
  - docker exec -u root build apt-get -q -y --no-install-recommends install make gcc gcc-multilib gcc-mingw-w64 autoconf automake libtool pkg-config ca-certificates wget patch sed git-core golang-go moreutils zip
script:
  - docker exec build make -C /build 3rdparty-all
  - docker exec build make -C /build unit-test
  - suffix=
  - |
    if [ -n "$TRAVIS_PULL_REQUEST" ]; then
      suffix="-${TRAVIS_COMMIT}-pr${TRAVIS_PULL_REQUEST}"
    elif [ -z "$TRAVIS_TAG" ]; then
      suffix="-$TRAVIS_COMMIT"
    fi
  - docker exec build make -C /build release VERSIONSUFFIX=$suffix
after_script:
  - docker exec build ls -l /build /build/_3rdparty/archive
  - docker exec build ls -lR /build/_build
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: ZYr2KB6gzZnwcEq+05QU01VomEFZCn/nAonMFpxqGpqzm/MimLHRfqAGTZkVnC5xByoCEaWOKXao9OVAhRpZjVepB4FtxqEVHei1MqCtI+S7ZTf+/FyIXd+W9+5KvAPT/sQ3SH2oaCL1/JKwmxclq4ikngHlHX5xiHMUGb/I14rgj60NvqDPxT/9MdrM0hpnMFxKwzuA1qKYvFQYqhKUOKc7IzjVOx6M7e+f3nOi2dAFY0R1iF5ipw/e1EEbs3EIYFaRUY7vajb2UpnoYloQZ1M0psfUWrLGnOrInn8Axxs3bFHl/PYoVMGfHKTSP2vb4QyqX/Y7ksj0WacdM9GLq/CZp3/6bmRJym8c/U3eBdbrWW1SpOBNBMBaoUoYn8twcBGn8c1x2vlNkBACXty5n+XL5cQ2zC/PspenWC9PLH+KHNlMpueEMuNE/4R/DHogLmC5V/LWnzp2WMhxfG3ZXqJaMwmiZEPb2TR89Yb2Toa0KGX398/FZoQVBeSg932P+IAETOW2oXSF6lw7eq7GHBvCFYIBqIz2DxBUF9dyhj/8Lw50Hi85OAVulmbQh5reZxSfltRBfyxPZPpLzFGNu6knHmaZ81IsKwhX0Rt2MUtak2viyc6Rs+2alLyxk1su0ZH4bRR8QzgEaIixML+5a6MTB0xTBh45F6X7kslCZOs=
  file_glob: true
  file: spyre-*.zip
  on:
    repo: spyre-project/spyre
    all_branches: false
    tags: true
